"""inition comm

Revision ID: 93837c7c660f
Revises: 
Create Date: 2024-12-25 22:17:30.492244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93837c7c660f'
down_revision = None
branch_labels = None
depends_on = None

def data_upgrades():
    pass
    t_users = sa.sql.table(
        'users',
        sa.sql.column('id', sa.Integer),
        sa.sql.column('first_name', sa.String),
        sa.sql.column('last_name', sa.String),
        sa.sql.column('middle_name', sa.String),
        sa.sql.column('login', sa.String),
        sa.sql.column('password', sa.String)
    )
    op.bulk_insert(t_users,
        [
            {
                'id': 1,
                'first_name': 'Иван',
                'last_name': 'Иванов',
                'middle_name': 'Иванович',
                'login': 'user123',
                'password': 'scrypt:32768:8:1$1PxN6hUaG9hHshbU$f3043f41e0276c7e967589ab3afa07351a2c2ba1eb459e3fec9372ae03a8882fa6545bec8c35742fcdb809bc5a8c89cad5431e11d5afc460246e875baeb3a6ac'  
            }
        ]
    )

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    data_upgrades()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
