SECRET_KEY = 'test'
# MYSQL_USER = 'test'
# MYSQL_PASSWORD = 'test'
# MYSQL_HOST = '172.16.0.11'
# MYSQL_DATABASE = 'test'

SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://test:test@192.168.1.4/test'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True